# Uncomment the next line to define a global platform for your project


platform :ios, '8.0'


source 'https://github.com/fishmwei/react-native-spec.git'

def crashreact0493
    pod 'yoga', '0.49.3.React'
    
      pod 'React', '~>0.49.3'
      pod 'React/Core', '~>0.49.3'
      #pod 'React/CxxBridge', '~>0.49.3'
      pod 'React/BatchedBridge', '~>0.49.3'
      pod 'React/RCTText', '~>0.49.3'
      pod 'React/RCTNetwork', '~>0.49.3'
      pod 'React/RCTWebSocket', '~>0.49.3'
      pod 'React/RCTImage', '~>0.49.3'
      pod 'React/DevSupport', '~>0.49.3'
      pod 'React/jschelpers', '~>0.49.3'
      pod 'React/cxxreact', '~>0.49.3'
      pod 'React/ART', '~>0.49.3'
      pod 'React/RCTActionSheet', '~>0.49.3'
      pod 'React/RCTAnimation', '~>0.49.3'
    
        #pod 'React/RCTBlob', '~>0.49.3'
      pod 'React/RCTCameraRoll', '~>0.49.3'
      pod 'React/RCTGeolocation', '~>0.49.3'
    
      pod 'React/RCTPushNotification', '~>0.49.3'
      pod 'React/RCTSettings', '~>0.49.3'
      pod 'React/RCTVibration', '~>0.49.3'
      pod 'React/fishhook', '~>0.49.3'
      pod 'React/RCTLinkingIOS', '~>0.49.3'
    
    pod 'DoubleConversion', '1.1.5'
    pod 'GLog', '0.3.4'
    pod 'Folly', '2016.09.26.00'
    pod 'boost', '1.63.0'
end



def fixreact0493
  pod 'yoga', '0.49.3.React'
  
  pod 'React', :git=>'https://github.com/fishmwei/react-native.git', :branch=>'feature/0.49.3-spec', :subspecs => [
  'Core',
'cxxreact_legacy',
'BatchedBridge', # use this
  #'CxxBridge',
  'RCTText',
  'RCTNetwork',
  'RCTWebSocket',
  'RCTImage',
  'DevSupport',
  'jschelpers',
  'cxxreact',
  'ART',
  'RCTActionSheet',
  'RCTAnimation',
  'RCTCameraRoll',
  'RCTGeolocation',
  'RCTPushNotification',
  'RCTSettings',
  'RCTVibration',
  'fishhook',
  'RCTLinkingIOS',
  ]
  
  pod 'DoubleConversion', '1.1.5'
  pod 'GLog', '0.3.4'
  pod 'Folly', '2016.09.26.00' 
  pod 'boost', '1.63.0'
end


target 'TestRN493' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

    crashreact0493
    #fixreact0493


end
