# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestYogac11' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestYogac11
  pod 'yoga', :path=>'./js/node_modules/react-native/ReactCommon/yoga'

end
